"""Add NHL box score columns

Revision ID: 0abd1b17bb58
Revises: a3f2c8d91b04
Create Date: 2026-03-05 19:36:19.791495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0abd1b17bb58'
down_revision: Union[str, Sequence[str], None] = 'a3f2c8d91b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_sog', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_sog', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_ppg', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_ppg', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_ppo', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_ppo', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_pim', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_pim', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_hits', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_hits', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_blocks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_blocks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_faceoff_pct', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('away_faceoff_pct', sa.Float(), nullable=True))
    op.alter_column('odds', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('picks', 'graded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sentiment', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentiment', 'analyzed_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('picks', 'graded_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('odds', 'fetched_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('games', 'away_faceoff_pct')
    op.drop_column('games', 'home_faceoff_pct')
    op.drop_column('games', 'away_blocks')
    op.drop_column('games', 'home_blocks')
    op.drop_column('games', 'away_hits')
    op.drop_column('games', 'home_hits')
    op.drop_column('games', 'away_pim')
    op.drop_column('games', 'home_pim')
    op.drop_column('games', 'away_ppo')
    op.drop_column('games', 'home_ppo')
    op.drop_column('games', 'away_ppg')
    op.drop_column('games', 'home_ppg')
    op.drop_column('games', 'away_sog')
    op.drop_column('games', 'home_sog')
    # ### end Alembic commands ###
