"""Add MLB box score columns

Revision ID: 7666f926b7d0
Revises: 0abd1b17bb58
Create Date: 2026-03-06 13:34:32.427162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7666f926b7d0'
down_revision: Union[str, Sequence[str], None] = '0abd1b17bb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_runs_scored', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_runs_scored', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_home_runs', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_home_runs', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_rbi', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_rbi', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_strikeouts', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_strikeouts', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_walks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_walks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_doubles', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_doubles', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_triples', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_triples', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_stolen_bases', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_stolen_bases', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_earned_runs', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_earned_runs', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_pitching_strikeouts', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_pitching_strikeouts', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_pitching_walks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_pitching_walks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_hits_allowed', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_hits_allowed', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_innings_pitched', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('away_innings_pitched', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'away_innings_pitched')
    op.drop_column('games', 'home_innings_pitched')
    op.drop_column('games', 'away_hits_allowed')
    op.drop_column('games', 'home_hits_allowed')
    op.drop_column('games', 'away_pitching_walks')
    op.drop_column('games', 'home_pitching_walks')
    op.drop_column('games', 'away_pitching_strikeouts')
    op.drop_column('games', 'home_pitching_strikeouts')
    op.drop_column('games', 'away_earned_runs')
    op.drop_column('games', 'home_earned_runs')
    op.drop_column('games', 'away_stolen_bases')
    op.drop_column('games', 'home_stolen_bases')
    op.drop_column('games', 'away_triples')
    op.drop_column('games', 'home_triples')
    op.drop_column('games', 'away_doubles')
    op.drop_column('games', 'home_doubles')
    op.drop_column('games', 'away_walks')
    op.drop_column('games', 'home_walks')
    op.drop_column('games', 'away_strikeouts')
    op.drop_column('games', 'home_strikeouts')
    op.drop_column('games', 'away_rbi')
    op.drop_column('games', 'home_rbi')
    op.drop_column('games', 'away_home_runs')
    op.drop_column('games', 'home_home_runs')
    op.drop_column('games', 'away_runs_scored')
    op.drop_column('games', 'home_runs_scored')
    # ### end Alembic commands ###
